export const ZONAS_CORDOBA = [
  "Nueva Córdoba",
  "Cerro de las Rosas",
  "Alta Córdoba",
  "Alberdi",
  "Güemes",
  "General Paz",
  "Jardín",
  "Urca",
  "Villa Cabrera",
  "Poeta Lugones",
  "Quebrada de las Rosas",
  "Villa Belgrano",
  "Argüello",
  "Villa Warcalde",
  "Centro",
  "San Vicente",
  "Los Boulevares",
  "Valle Escondido",
  "Manantiales",
  "Jockey Club",
  "Villa Allende",
  "Mendiolaza",
  "Río Ceballos",
  "La Calera",
  "Unquillo",
] as const;
